spring:
  profiles:
    #    active: local
    active: dev
  application:
    name: monitor

machine:
#  url: http://127.0.0.1:8084/web/getChargeInfo
  url: http://192.168.31.165:8084/web/getChargeInfo

connect:
  # 树莓派
  #  url: http://127.0.0.1:8084/web/isSMPConnectNotice
  # Cassia
#  url: http://127.0.0.1:8084/web/isCassiaConnectNotice
  url: http://192.168.31.165:8084/web/isCassiaConnectNotice
#  start: http://127.0.0.1:8084/web/enableNotice
  start: http://192.168.31.165:8084/web/enableNotice