server:
  port: 8081
  servlet:
    context-path: /yjjk
#  ssl:
#    key-store: classpath:tonticn.cn.jks
#    key-store-password: pgu6w992l4evgt2
#    keyStoreType: JKS

spring:
  datasource:
    username: yjjk
    password: YJjk_2018
    url: jdbc:mysql://192.168.31.84:3306/monitor2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    #    url: jdbc:mysql://192.168.31.229:3306/monitor2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    #    url: jdbc:mysql://192.168.31.185:3306/monitor2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  jackson:
  #    default-property-inclusion: non_null
  #    druid:
  #      initial-size: 8
  #        min-idle: 1
  #        max-active: 20
  #        max-wait: 60000
  #        time-between-eviction-runsMillis: 60000
  #        min-evictable-idle-timeMillis: 300000
  #        validation-query: select 'x' FROM DUAL
  #        test-while-idle: true
  #        test-on-borrow: false
  #        test-on-return: false
  #        pool-prepared-statements: true
  #        max-open-prepared-statements: 20
  #        max-pool-prepared-statement-per-connection-size: 20
  #        filters: stat
  #        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #        use-global-data-source-stat: true
  servlet:
    multipart:
      max-file-size: 2MB


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yjjk.monitor.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

#showSql
logging:
  file: logs/${spring.application.name}.log
  level:
    com:
      yjjk:
        monitor:
          mapper:
            DEBUG
web:
  upload-path: E:\YJJKProject\UploadImg

machine:
  #  address: http://192.168.31.165:8084
  address: http://192.168.31.165:8084
  url: /web/getChargeInfo
  repeater: /web/getRepeaterChargeInfo

connect:
  # Cassia
  #  address: http://192.168.31.165:8084
  address: http://192.168.31.165:8084
  url: /web/isCassiaConnectNotice
  start: /web/enableNotice
  machine: /web/getCassiaOnlineList